// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pelt_pcf_
std::vector<int> pelt_pcf_(const std::vector<double>& y, int kmin, double gamma, const std::vector<int>& allowed_breakpoints);
RcppExport SEXP _segmentation_pelt_pcf_(SEXP ySEXP, SEXP kminSEXP, SEXP gammaSEXP, SEXP allowed_breakpointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type allowed_breakpoints(allowed_breakpointsSEXP);
    rcpp_result_gen = Rcpp::wrap(pelt_pcf_(y, kmin, gamma, allowed_breakpoints));
    return rcpp_result_gen;
END_RCPP
}
// pelt_multipcf_
std::vector<int> pelt_multipcf_(const NumericMatrix& y, int kmin, double gamma, const std::vector<int>& allowed_breakpoints);
RcppExport SEXP _segmentation_pelt_multipcf_(SEXP ySEXP, SEXP kminSEXP, SEXP gammaSEXP, SEXP allowed_breakpointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type allowed_breakpoints(allowed_breakpointsSEXP);
    rcpp_result_gen = Rcpp::wrap(pelt_multipcf_(y, kmin, gamma, allowed_breakpoints));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_segmentation_pelt_pcf_", (DL_FUNC) &_segmentation_pelt_pcf_, 4},
    {"_segmentation_pelt_multipcf_", (DL_FUNC) &_segmentation_pelt_multipcf_, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_segmentation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
