# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pelt_pcf_ <- function(y, kmin, gamma, allowed_breakpoints, constrain_integer = FALSE) {
    .Call(`_segmentation_pelt_pcf_`, y, kmin, gamma, allowed_breakpoints, constrain_integer)
}

pelt_multipcf_ <- function(y, kmin, gamma, allowed_breakpoints, constrain_integer = FALSE) {
    .Call(`_segmentation_pelt_multipcf_`, y, kmin, gamma, allowed_breakpoints, constrain_integer)
}

