# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Crossprod <- function(x, y) {
    .Call(`_segmentation_Crossprod`, x, y)
}

Quantile <- function(x, p) {
    .Call(`_segmentation_Quantile`, x, p)
}

sawMarkMCpp <- function(x, L, frac1, frac2) {
    .Call(`_segmentation_sawMarkMCpp`, x, L, frac1, frac2)
}

compactMultiCpp <- function(y, mark) {
    .Call(`_segmentation_compactMultiCpp`, y, mark)
}

markMultiPottsCpp <- function(nr, sum, gamma, subSize) {
    .Call(`_segmentation_markMultiPottsCpp`, nr, sum, gamma, subSize)
}

multiPCFcompactCpp <- function(nr, sum, gamma) {
    .Call(`_segmentation_multiPCFcompactCpp`, nr, sum, gamma)
}

expandMultiCpp <- function(nProbes, nSamples, lengthInt, mean) {
    .Call(`_segmentation_expandMultiCpp`, nProbes, nSamples, lengthInt, mean)
}

filterMarkCpp <- function(x, kmin, L, L2, frac1, frac2, frac3, thres) {
    .Call(`_segmentation_filterMarkCpp`, x, kmin, L, L2, frac1, frac2, frac3, thres)
}

compactCpp <- function(y, mark) {
    .Call(`_segmentation_compactCpp`, y, mark)
}

findEstCpp <- function(bestSplit, N, Nr, Sum, yest) {
    .Call(`_segmentation_findEstCpp`, bestSplit, N, Nr, Sum, yest)
}

PottsCompactCpp <- function(kmin, gamma, nr, res, yest) {
    .Call(`_segmentation_PottsCompactCpp`, kmin, gamma, nr, res, yest)
}

findMarksCpp <- function(markSub, Nr, subsize) {
    .Call(`_segmentation_findMarksCpp`, markSub, Nr, subsize)
}

markWithPottsCpp <- function(kmin, gamma, nr, res, subsize) {
    .Call(`_segmentation_markWithPottsCpp`, kmin, gamma, nr, res, subsize)
}

